fs: 48000
room_dim:
- 10.0
- 10.0
- 2.75
room_floor_m2: 100.0
source_pos:
- 6.414
- 5.0
- 2.55
azimuth_deg: 0.0
elevation_deg: 35.98
source_distance_m: 2.0
fullband_T30_ms: 142.8
mic: tetra r=0.05
target_asl_dB: 90.0
foa_format: SN3D ACN (WXYZ)
